name: example
description: Examples for async_redux.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.4
  async_redux:
    path: ../
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
