name: async_redux
description: Redux without the boilerplate, tailored for Flutter. Easy to learn, to use and test. Allows for both sync and async reducers.
version: 21.0.0
homepage: https://github.com/marcglasberg/async_redux
# author: Marcelo Glasberg <marcglasberg@gmail.com>

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  path_provider: ^2.1.1
  file: ^7.0.0
  weak_map: ^3.0.0
  fast_immutable_collections: ^9.2.0
  collection: ^1.18.0
  logging: ^1.2.0
  path: ^1.8.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

