name: async_redux
description: Redux without the boilerplate, tailored for Flutter. Easy to learn, to use and test. Allows for both sync and async reducers.
version: 13.3.1
homepage: https://github.com/marcglasberg/async_redux
# author: Marcelo Glasberg <marcglasberg@gmail.com>

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  path_provider: ^2.0.8
  file: ^6.1.2
  weak_map: ^2.0.3
  fast_immutable_collections: ^7.1.2
  collection: ^1.15.0
  logging: ^1.0.2
  path: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.0
  flutter_test:
    sdk: flutter

flutter:

