name: async_redux
description: Redux state management. An optimized Redux version, which is very easy to learn and use, yet powerful and tailored for Flutter. It allows both sync and async reducers.
version: 22.1.0-dev.2
# author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/async_redux
topics:
  - redux
  - state-management

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  async_redux_core: ^1.2.0
  meta: ^1.11.0
  path_provider: ^2.1.1
  file: ^7.0.0
  weak_map: ^3.0.0
  fast_immutable_collections: ^10.1.2
  connectivity_plus: ^5.0.2
  collection: ^1.18.0
  logging: ^1.2.0
  path: ^1.8.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

