name: async_redux
description: Redux without the boilerplate, tailored for Flutter. Easy to learn, to use and test. Allows for both sync and async reducers.
version: 10.0.0
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/async_redux

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.1
  file: ^6.0.0
  weak_map: ^2.0.1
  fast_immutable_collections: ^4.0.6
  collection: ^1.15.0
  meta: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.5
  async: ^2.5.0
  flutter_test:
    sdk: flutter

flutter:

