name: async_redux
description: Redux without the boilerplate, tailored for Flutter. Easy to learn, to use and test. Allows for both sync and async reducers.
version: 8.0.0
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/async_redux

environment:
  sdk: ">=2.9.3 <3.0.0"

dependencies:
  logging: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.0-nullsafety.1
  file: ^6.0.0-nullsafety.3
  weak_map: ^2.0.0-nullsafety.1
  fast_immutable_collections: ^2.0.0-nullsafety.1
  meta: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.16.3
  async: ^2.5.0
  flutter_test:
    sdk: flutter

flutter:

