name: async_redux
description: Redux without the boilerplate, tailored for Flutter. Easy to learn, to use and test. Allows for both sync and async reducers.
version: 19.0.0
homepage: https://github.com/marcglasberg/async_redux
# author: Marcelo Glasberg <marcglasberg@gmail.com>

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  path_provider: ^2.0.13
  file: ^6.1.4
  weak_map: ^2.1.0
  fast_immutable_collections: ^9.0.0
  collection: ^1.17.0
  logging: ^1.1.1
  path: ^1.8.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

